name: Upload APK

on:
  workflow_dispatch:
    inputs:
      apk_name:
        description: 'apk name'
        required: true
        default: 'deltachat_own_'

jobs:
  build:
    name: Upload APK
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
        with:
          working-directory: jni/deltachat-core-rust
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: android-actions/setup-android@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23c

      - name: Compile core
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          export PATH="${PATH}:${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/"
          scripts/install-toolchains.sh && scripts/ndk-make.sh arm64-v8a

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
        run: |
          echo "$ENCODED_STRING" > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks

      - name: Build APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.apk_name }}.apk
          path: 'build/outputs/apk/fat/debug/*.apk'
